In [1]:
import numpy as np

In [2]:
# NumPy Mathematical Functions

array_sum = np.sum([10, 20])
array_sum

30

In [3]:
a, b, c = 10,20,30

In [4]:
a

10

In [5]:
b

20

In [6]:
c

30

In [7]:
# Sum without axis - sum of all elements

abc = np.sum([a,b,c])
abc

60

In [10]:
np.sum([[10, 20],[50, 60]])

140

In [11]:
# Sum with axis=0 - sum of corresponding elements / Col wise sum

np.sum([[10, 20],[50, 60]], axis=0)

array([60, 80])

In [12]:
# Sum with axis=1 - adding elements within array / sum of emements group by array / Row wise sum

np.sum([[0, 2],[0, 6]], axis=1)

array([2, 6])

In [ ]:
np_a = [1, 2, 3]
np_b = [4, 5, 6]

In [18]:
# Sum of Arrays without axis - sum of all elements

a_plus_b = np.sum([np_a, np_b])
a_plus_b

21

In [17]:
# Sum of Arrays with axis=0 - sum of corresponding elements / Col wise sum

a_plus_b_axis_0 = np.sum([np_a, np_b], axis=0)
a_plus_b_axis_0 

array([5, 7, 9])

In [19]:
# Sum of Arrays with axis=1  - adding elements within array / sum of emements group by array / Row wise sum

a_plus_b_axis_1 = np.sum([np_a, np_b], axis=1)
a_plus_b_axis_1 

array([ 6, 15])

In [23]:
# Substraction of Arrays - Col wise minus

b_minus_a = np.subtract(np_b, np_a)
b_minus_a

array([3, 3, 3])

In [27]:
# Subtract doesn't support - axis paramete

b_minus_a = np.subtract(np_b, np_a, axis=0)
b_minus_a

TypeError: 'axis' is an invalid keyword to ufunc 'subtract'

In [25]:
# Multiplication of Arrays - Col wise multiplication

a_multiplys_b = np.multiply(np_a, np_b)
a_multiplys_b

array([ 4, 10, 18])

In [28]:
# Multiplication doesn't support - axis paramete

a_multiplys_b_axis_0 = np.multiply(np_a, np_b, axis=0)
a_multiplys_b_axis_0

TypeError: 'axis' is an invalid keyword to ufunc 'multiply'

In [30]:
# Division of Arrays - Col wise division

b_divide_a = np.divide(np_b, np_a)
b_divide_a

array([4. , 2.5, 2. ])

In [31]:
# Division doesn't support - axis paramete

b_divide_a_axis_0 = np.divide(np_b, np_a, axis=0)
b_divide_a_axis_0

TypeError: 'axis' is an invalid keyword to ufunc 'true_divide'

In [38]:
angles = [0, 30, 45, 60, 90]

In [39]:
print(np.sin(angles))

[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]


In [40]:
print(np.cos(angles))

[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362]


In [41]:
print(np.tan(angles))

[ 0.         -6.4053312   1.61977519  0.32004039 -1.99520041]


In [43]:
# Array Comparision - Element wise

aa = np.array([1,2,3])
bb = np.array([1,2,3])
cc = np.array([1,2,9])

In [44]:
np.equal(aa,bb)

array([ True,  True,  True])

In [45]:
np.equal(aa,cc)

array([ True,  True, False])

In [46]:
# Array Comparision - Array wise

np.array_equal(aa,bb)

True

In [47]:
np.array_equal(aa,cc)

False

In [49]:
# Aggregrate Functions - works on single array

aaa = np.array([1,2,4])

In [50]:
print(np.sum(aaa))

7


In [51]:
print(np.min(aaa))

1


In [52]:
print(np.max(aaa))

4


In [53]:
print(np.mean(aaa))

2.3333333333333335


In [54]:
print(np.median(aaa))

2.0


In [55]:
# Correlation Coefficient

print(np.corrcoef(aaa))  

1.0


In [56]:
# Standard Deviation

print(np.std(aaa))

1.247219128924647


In [58]:
array_a = np.array([[1,2,3],[4,5,6]])
array_b = np.array([[3,4,5],[5,6,7]])

In [59]:
print(array_a)

[[1 2 3]
 [4 5 6]]


In [60]:
print(array_b)

[[3 4 5]
 [5 6 7]]


In [63]:
# Aggregrate Function - Sum - without axis

print(np.sum([array_a, array_b]))

51


In [64]:
# Aggregrate Function - Sum - with axis=0
 
print(np.sum([array_a, array_b], axis=0))

[[ 4  6  8]
 [ 9 11 13]]


In [65]:
# Aggregrate Function - Sum - with axis=1
 
print(np.sum([array_a, array_b], axis=1))

[[ 5  7  9]
 [ 8 10 12]]


In [ ]:
# Arrays with concept of Broadcasting

