In [1]:
!pip install numpy # ! - invoking operation from cmd (terminal)

You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [13]:
!pip install numpy --upgrade pip

Requirement already up-to-date: numpy in c:\users\ns.prasanth\appdata\local\continuum\anaconda3\lib\site-packages (1.18.1)


ERROR: To modify pip, please run the following command:
c:\users\ns.prasanth\appdata\local\continuum\anaconda3\python.exe -m pip install numpy --upgrade pip
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [2]:
!pip install numpy --upgrade

Requirement already up-to-date: numpy in c:\users\ns.prasanth\appdata\local\continuum\anaconda3\lib\site-packages (1.18.1)


You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [3]:
# Numpy - Numerical computing library / package, Numpy suppors - Multi-Dimentioanl Arrays

import numpy as np # np is alias for numpy

In [2]:
array_one = np.array[1,2,3,4,5]
array_one

TypeError: 'builtin_function_or_method' object is not subscriptable

In [3]:
type(array_one)

NameError: name 'array_one' is not defined

In [28]:
# Creating NumPy Array from Python List

a_1 = np.array([1, 2, 3])
print(a_1)

[1 2 3]


In [29]:
# Creating NumPy Array from Python Set

a_2 = np.array((1, 2, 3))
print(a_2)

[1 2 3]


In [31]:
# Edit NumPy array like in List

a_1[2] = 4
a_1

array([1, 2, 4])

In [ ]:
# Difference between - List & Array - which is optimized

# array is much more optimized way to operations

# reason - vectarization

In [4]:
numbers = [1,2,3,4,5]
array_two = np.array(numbers)
array_two

array([1, 2, 3, 4, 5])

In [5]:
array_of_zeros = np.zeros((3,4)) # Datatype of array by default consider as Floats
array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
array_of_ones = np.ones((3,4))
array_of_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
# Converting float array to int - include int16 / int32

array_of_ones_int = np.ones((3,4), dtype=np.int16)
array_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [6]:
# Giving Range through arrange()

np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
# Print only even number betwen 1 & 30 from an array

np.arange(2,31,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [11]:
# To know the dimention of the array - shape

e = np.array([(1,2,3),(4,5,6)])
e

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
e.shape

(2, 3)

In [33]:
x = np.array([(1,2,3),(4,5,6),(7,8,9)])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
# Displaying a specific row 

x[0,:]

array([1, 2, 3])

In [41]:
# Displaying a specific col 

x[:,1]

array([2, 5, 8])

In [39]:
# Displaying a col 

x[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [14]:
x.shape

(3, 3)

In [17]:
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [19]:
a.shape # 1 d array

(15,)

In [6]:
b = np.arange(1,9)
b

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
b.shape # 1 d array

(8,)

In [24]:
# Reshaping array Note : reshape(4,2) should satsfy arange(1,9) i.,e reshape dimentions 4 x 2 = 8 should be equal to arrange 8

b = np.arange(1,9).reshape(4,2)
b

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [25]:
b.shape

(4, 2)

In [26]:
# Reshaping array Note : reshape(5,6) didn't satsfy arange(1,9) i.,e reshape dimentions 5 x 6 = 30 is not equal to arrange 8

c = np.arange(1,9).reshape(5,6)
c

ValueError: cannot reshape array of size 8 into shape (5,6)

In [11]:
# Universal operation in NupPy

# 1 Trinometric Functions

angles = np.array([0,30,40,60,90])

In [12]:
# radians = angles * pi/180

angle_radians = np.radians(angles)
angle_radians

array([0.        , 0.52359878, 0.6981317 , 1.04719755, 1.57079633])

In [13]:
print(np.sin(angle_radians))

[0.         0.5        0.64278761 0.8660254  1.        ]


In [14]:
print(np.cos(angle_radians))

[1.00000000e+00 8.66025404e-01 7.66044443e-01 5.00000000e-01
 6.12323400e-17]


In [15]:
# 1 Stasticas Functions

test_scores = np.array([1,3,5,7,9,11,13])

# Mean = Average

print(np.mean(test_scores))

7.0


In [16]:
# Median = Mid number

print(np.median(test_scores)) 

7.0


In [18]:
# Arthimatic Functions

a = np.array([10,10,10])
b = np.array([5,5,5])

In [19]:
c = a + b
c

array([15, 15, 15])

In [20]:
d = a - b
d

array([5, 5, 5])

In [21]:
e = a * b
e

array([50, 50, 50])

In [22]:
a < 35

array([ True,  True,  True])

In [23]:
a > 25

array([False, False, False])

In [24]:
# Squaring

a**2

array([100, 100, 100], dtype=int32)

In [25]:
# un-array operators

ages = np.array([12,15,18,20])

In [26]:
ages.sum()

65

In [27]:
ages.min()

12

In [28]:
ages.max()

20

In [29]:
numbers = np.arange(12).reshape(3,4)
numbers

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
# in a 2D array, axis_0 represents Cols & axis_1 represents Rows

sum_axis_0 = numbers.sum(axis = 0)
sum_axis_0

array([12, 15, 18, 21])

In [31]:
sum_axis_1 = numbers.sum(axis = 1)
sum_axis_1

array([ 6, 22, 38])

In [32]:
array_a = np.arange(6)
array_a

array([0, 1, 2, 3, 4, 5])

In [33]:
array_b = np.arange(4)
array_b

array([0, 1, 2, 3])

In [35]:
# To perform mathematical operations (add, minus,...) on arrays - size of the array should be same

array_c = array_a + array_b
array_c

ValueError: operands could not be broadcast together with shapes (6,) (4,) 

In [48]:
# Reading data from file

salaries = np.genfromtxt('salary.csv',delimiter = ',')

In [49]:
salaries

array([60000., 58000., 56967., ..., 54647., 25000., 70000.])

In [13]:
salaries.shape

(1147,)

In [22]:
mean_sal = np.mean(salaries)
print(f'Mean of Salary : {mean_sal}')

Mean of Salary : 55894.53879686138


In [23]:
median_sal = np.median(salaries)
print(f'Median of Salary : {median_sal}')

Median of Salary : 48000.0


In [24]:
standard_deviation_sal = np.std(salaries)
print(f'Standard Deviation of Salary : {standard_deviation_sal}')

Standard Deviation of Salary : 55170.37550939316


In [25]:
variance_sal = np.var(salaries)
print(f'Variance of Salary : {variance_sal}')

Variance of Salary : 3043770333.8474483
