In [1]:
!pip install numpy # ! - invoking operation from cmd (terminal)

You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [13]:
!pip install numpy --upgrade pip

Requirement already up-to-date: numpy in c:\users\ns.prasanth\appdata\local\continuum\anaconda3\lib\site-packages (1.18.1)


ERROR: To modify pip, please run the following command:
c:\users\ns.prasanth\appdata\local\continuum\anaconda3\python.exe -m pip install numpy --upgrade pip
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [2]:
!pip install numpy --upgrade

Requirement already up-to-date: numpy in c:\users\ns.prasanth\appdata\local\continuum\anaconda3\lib\site-packages (1.18.1)


You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [1]:
# Numpy - Numerical computing library / package, Numpy suppors - Multi-Dimentioanl Arrays

import numpy as np # np is alias for numpy

In [3]:
array_one = np.array([1,2,3,4,5])
array_one

array([1, 2, 3, 4, 5])

In [4]:
type(array_one)

numpy.ndarray

In [28]:
# Creating NumPy Array from Python List

a_1 = np.array([1, 2, 3])
print(a_1)

[1 2 3]


In [29]:
# Creating NumPy Array from Python Set

a_2 = np.array((1, 2, 3))
print(a_2)

[1 2 3]


In [31]:
# Edit NumPy array like in List

a_1[2] = 4
a_1

array([1, 2, 4])

In [ ]:
# Difference between - List & Array - which is optimized

# array is much more optimized way to operations

# reason - vectarization

In [4]:
numbers = [1,2,3,4,5]
array_two = np.array(numbers)
array_two

array([1, 2, 3, 4, 5])

In [5]:
array_of_zeros = np.zeros((3,4)) # Datatype of array by default consider as Floats
array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
array_of_ones = np.ones((3,4))
array_of_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
# Converting float array to int - include int16 / int32

array_of_ones_int = np.ones((3,4), dtype=np.int16)
array_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [6]:
# Giving Range through arrange()

np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
# Print only even number betwen 1 & 30 from an array

np.arange(2,31,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [11]:
# To know the dimention of the array - shape

e = np.array([(1,2,3),(4,5,6)])
e

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
e.shape

(2, 3)

In [33]:
x = np.array([(1,2,3),(4,5,6),(7,8,9)])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
# Displaying a specific row 

x[0,:]

array([1, 2, 3])

In [41]:
# Displaying a specific col 

x[:,1]

array([2, 5, 8])

In [39]:
# Displaying a col 

x[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [14]:
x.shape

(3, 3)

In [17]:
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [19]:
a.shape # 1 d array

(15,)

In [6]:
b = np.arange(1,9)
b

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
b.shape # 1 d array

(8,)

In [24]:
# Reshaping array Note : reshape(4,2) should satsfy arange(1,9) i.,e reshape dimentions 4 x 2 = 8 should be equal to arrange 8

b = np.arange(1,9).reshape(4,2)
b

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [25]:
b.shape

(4, 2)

In [26]:
# Reshaping array Note : reshape(5,6) didn't satsfy arange(1,9) i.,e reshape dimentions 5 x 6 = 30 is not equal to arrange 8

c = np.arange(1,9).reshape(5,6)
c

ValueError: cannot reshape array of size 8 into shape (5,6)

In [11]:
# Universal operation in NupPy

# 1 Trinometric Functions

angles = np.array([0,30,40,60,90])

In [12]:
# radians = angles * pi/180

angle_radians = np.radians(angles)
angle_radians

array([0.        , 0.52359878, 0.6981317 , 1.04719755, 1.57079633])

In [13]:
print(np.sin(angle_radians))

[0.         0.5        0.64278761 0.8660254  1.        ]


In [14]:
print(np.cos(angle_radians))

[1.00000000e+00 8.66025404e-01 7.66044443e-01 5.00000000e-01
 6.12323400e-17]


In [15]:
# 1 Stasticas Functions

test_scores = np.array([1,3,5,7,9,11,13])

# Mean = Average

print(np.mean(test_scores))

7.0


In [16]:
# Median = Mid number

print(np.median(test_scores)) 

7.0


In [18]:
# Arthimatic Functions

a = np.array([10,10,10])
b = np.array([5,5,5])

In [19]:
c = a + b
c

array([15, 15, 15])

In [20]:
d = a - b
d

array([5, 5, 5])

In [21]:
e = a * b
e

array([50, 50, 50])

In [22]:
a < 35

array([ True,  True,  True])

In [23]:
a > 25

array([False, False, False])

In [24]:
# Squaring

a**2

array([100, 100, 100], dtype=int32)

In [25]:
# un-array operators

ages = np.array([12,15,18,20])

In [26]:
ages.sum()

65

In [27]:
ages.min()

12

In [28]:
ages.max()

20

In [29]:
numbers = np.arange(12).reshape(3,4)
numbers

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
# in a 2D array, axis_0 represents Cols & axis_1 represents Rows

sum_axis_0 = numbers.sum(axis = 0)
sum_axis_0

array([12, 15, 18, 21])

In [31]:
sum_axis_1 = numbers.sum(axis = 1)
sum_axis_1

array([ 6, 22, 38])

In [32]:
array_a = np.arange(6)
array_a

array([0, 1, 2, 3, 4, 5])

In [33]:
array_b = np.arange(4)
array_b

array([0, 1, 2, 3])

In [35]:
# To perform mathematical operations (add, minus,...) on arrays - size of the array should be same

array_c = array_a + array_b
array_c

ValueError: operands could not be broadcast together with shapes (6,) (4,) 

In [48]:
# Reading data from file

salaries = np.genfromtxt('salary.csv',delimiter = ',')

In [49]:
salaries

array([60000., 58000., 56967., ..., 54647., 25000., 70000.])

In [13]:
salaries.shape

(1147,)

In [22]:
mean_sal = np.mean(salaries)
print(f'Mean of Salary : {mean_sal}')

Mean of Salary : 55894.53879686138


In [23]:
median_sal = np.median(salaries)
print(f'Median of Salary : {median_sal}')

Median of Salary : 48000.0


In [24]:
standard_deviation_sal = np.std(salaries)
print(f'Standard Deviation of Salary : {standard_deviation_sal}')

Standard Deviation of Salary : 55170.37550939316


In [25]:
variance_sal = np.var(salaries)
print(f'Variance of Salary : {variance_sal}')

Variance of Salary : 3043770333.8474483


In [3]:
# Indexing & Slicing of an array

a = np.arange(11)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [4]:
a[2]

4

In [5]:
a[-2]

81

In [6]:
# Slicing of an array

a[2:7] # Starting from 2nd element to 6th element as last index (7) is excluded

array([ 4,  9, 16, 25, 36], dtype=int32)

In [7]:
# Slicing with step count

a[1:8:2]

array([ 1,  9, 25, 49], dtype=int32)

In [8]:
# Reversing an array

a[::-1]

array([100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0], dtype=int32)

In [10]:
# Array with mix of Datatypes

students = np.array([['a','b','c','d'],
                    [10, 20, 30, 40],
                    [50, 60, 70, 80]])

In [11]:
students

array([['a', 'b', 'c', 'd'],
       ['10', '20', '30', '40'],
       ['50', '60', '70', '80']], dtype='<U2')

In [ ]:
# < -> Little Indian
# > -> Big Indian
# u -> Unicode

In [12]:
students[0]

array(['a', 'b', 'c', 'd'], dtype='<U2')

In [13]:
students[1]

array(['10', '20', '30', '40'], dtype='<U2')

In [14]:
students[2]

array(['50', '60', '70', '80'], dtype='<U2')

In [15]:
students[0:1]

array([['a', 'b', 'c', 'd']], dtype='<U2')

In [16]:
students[0:2, 2:4] # rows from 0 to 1 & cols from 2 to 3

array([['c', 'd'],
       ['30', '40']], dtype='<U2')

In [19]:
# Iterate over arrays

x = np.arange(11)**2
x

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [20]:
# Printing square-root of an array

for i in x:
    print(i ** (1/2))

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [21]:
student = np.array([['a','b','c','d'],
                    [10, 20, 30, 40],
                    [50, 60, 70, 80]])

In [22]:
student

array([['a', 'b', 'c', 'd'],
       ['10', '20', '30', '40'],
       ['50', '60', '70', '80']], dtype='<U2')

In [23]:
for i in student:
    print('i = ', i)

i =  ['a' 'b' 'c' 'd']
i =  ['10' '20' '30' '40']
i =  ['50' '60' '70' '80']


In [24]:
for element in student.flatten():  # flatten() - Row major Flatting
    print(element)

a
b
c
d
10
20
30
40
50
60
70
80


In [26]:
for element in student.flatten(order = 'F'):  # flatten(order = 'F') - Column major Flatting
    print(element)

a
10
50
b
20
60
c
30
70
d
40
80


In [27]:
for element in student.flatten(order = 'T'): 
    print(element)

TypeError: order not understood

In [28]:
m = np.arange(12).reshape(3,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
for i in np.nditer(m): # Row major
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [31]:
for i in np.nditer(m, order = 'F'): # Col major
    print(i)

0
4
8
1
5
9
2
6
10
3
7
11


In [ ]:
# Difference between - Flatten & nditer

# Flatten - result an array - Values stores Permenent
# nditer - allows to iterate over array - Values stores Temperary 

In [3]:
# Shallow Copy - master data will impact

fruits = np.array(['apple','mango','graps','banana'])

In [4]:
basket_1 = fruits.view()
basket_2 = fruits.view()

In [5]:
print(basket_1)

['apple' 'mango' 'graps' 'banana']


In [6]:
print(basket_2)

['apple' 'mango' 'graps' 'banana']


In [7]:
print("IDs for the arrays are different")
print(id(fruits))

IDs for the arrays are different
1411655402000


In [8]:
print("IDs for baskets")
print(id(basket_1))
print(id(basket_2))

IDs for baskets
1411655402480
1411655401840


In [9]:
basket_1 is fruits

False

In [11]:
basket_1.base is fruits

True

In [12]:
# Changing elements in basket_1

basket_2[0] = 'kiwi' # Note : Changes effect original collection as well

In [13]:
fruits

array(['kiwi', 'mango', 'graps', 'banana'], dtype='<U6')

In [14]:
basket_2

array(['kiwi', 'mango', 'graps', 'banana'], dtype='<U6')

In [15]:
basket_2 = np.array(['a', 'b', 'c'])

In [16]:
# when we are creating an new array it will not effect the original (in this case - fruits)

basket_2

array(['a', 'b', 'c'], dtype='<U1')

In [17]:
fruits

array(['kiwi', 'mango', 'graps', 'banana'], dtype='<U6')

In [18]:
# Deep Copy - master data should not impact

basket = fruits.copy()

In [20]:
basket is fruits

False

In [21]:
# it dosn't share anything with the original (ie fruits)

basket.base is fruits

False

In [22]:
basket[0] = 'lemon'

In [23]:
basket

array(['lemon', 'mango', 'graps', 'banana'], dtype='<U6')

In [25]:
# original (fruits) will not effect

fruits

array(['kiwi', 'mango', 'graps', 'banana'], dtype='<U6')

In [26]:
basket.shape = 2,2

In [27]:
print(basket)

[['lemon' 'mango']
 ['graps' 'banana']]


In [8]:
# My NumPy Practice

np_a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np_a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
np_a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
type(np_a)

numpy.ndarray

In [13]:
np_a.shape

(3, 3)

In [14]:
# Difference between Arange & Linspace

# Arange

np_arrange = np.arange(12).reshape(3,4)
np_arrange

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
# Linspace - Arranging 'z' numbers between 'x' & 'y'

ls_1 = np.linspace(5,10,6)
ls_1

array([ 5.,  6.,  7.,  8.,  9., 10.])

In [20]:
ls_2 = np.linspace(5,10,10)
ls_2

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [21]:
ls_3 = np.linspace(5,10,5)
ls_3

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [22]:
ls_4 = np.linspace(5,10,2)
ls_4

array([ 5., 10.])

In [23]:
ls_5 = np.linspace(5,10,3)
ls_5

array([ 5. ,  7.5, 10. ])

In [24]:
ls_6 = np.linspace(0,10,6)
ls_6

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [26]:
ls_7 = np.linspace(0,10,6)
ls_7

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [27]:
ls_8 = np.linspace(0,10,8)
ls_8

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [28]:
# Initializing NumPy Array - Filling same number in an array of dimensions 'x' & 'y'

array_1 = np.full((2,2), 5)
array_1

array([[5, 5],
       [5, 5]])

In [29]:
array_2 = np.full((2,4), 6)
array_2

array([[6, 6, 6, 6],
       [6, 6, 6, 6]])

In [34]:
# Filling Random numbers in an array of dimensions 'x' & 'y'

array_3 = np.random.random((2,2))
array_3

array([[0.32032198, 0.35629776],
       [0.20695112, 0.26285456]])

In [37]:
array_4 = np.random.random((5,5))
array_4

array([[0.10771751, 0.20848227, 0.77048636, 0.01725496, 0.90842457],
       [0.3399887 , 0.74863561, 0.34270039, 0.7492734 , 0.24776524],
       [0.17033683, 0.65489337, 0.72810385, 0.46929092, 0.47459663],
       [0.80405676, 0.24064664, 0.77359418, 0.86026424, 0.2127861 ],
       [0.37735599, 0.13462944, 0.49840732, 0.3934015 , 0.89423117]])

In [39]:
# NumPy Array Inspection - shape - With 'shape' we can transpose the array

array_2

array([[6, 6, 6, 6],
       [6, 6, 6, 6]])

In [40]:
array_2.shape

(2, 4)

In [58]:
array_2.size

8

In [41]:
array_2.shape = (4, 2)

In [42]:
array_2

array([[6, 6],
       [6, 6],
       [6, 6],
       [6, 6]])

In [44]:
print(array_2.shape[0])

4


In [48]:
print(array_2.shape[:, 1])   

TypeError: tuple indices must be integers or slices, not tuple

In [43]:
array_2.shape = (3,3)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [49]:
array_5 = np.arange(1,17).reshape(4,4)
array_5

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [50]:
array_5.shape = (2, 8)
array_5

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [51]:
array_5.shape = (8, 2)
array_5

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [52]:
array_5.shape = (16, 1)
array_5

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16]])

In [53]:
array_5.shape = (3, 3)
array_5

ValueError: cannot reshape array of size 16 into shape (3,3)

In [55]:
array_6 = np.arange(24)
array_6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [57]:
# Size of the array - size

array_6.size

24

In [59]:
# Dimension of the array - ndim

array_7 = np.arange(24)
array_7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [61]:
array_7.ndim

1

In [62]:
array_8 = array_7.reshape(2,4,3)
array_8

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [63]:
array_8.ndim

3

In [64]:
array_9 = np.arange(48).reshape(2,2,4,3)
array_9

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]]],


       [[[24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44],
         [45, 46, 47]]]])

In [65]:
array_9.ndim

4

In [66]:
# We can't change the dimensions of the array

array_9.ndim = 3

AttributeError: attribute 'ndim' of 'numpy.ndarray' objects is not writable

In [68]:
array_10 = np.arange(24)
array_10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [69]:
array_10.size

24

In [70]:
print(array_10.size)

24


In [71]:
# Datatype of an array - dtype

array_10.dtype

dtype('int32')

In [72]:
array_11 = array_10.reshape(3,4,2)
array_11

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [73]:
array_11.dtype

dtype('int32')

In [74]:
array_12 = np.linspace(5,7,11)
array_12

array([5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. ])

In [75]:
array_12.dtype

dtype('float64')